[cluster]
node_id = 3
listen_address = "0.0.0.0:9083"
initial_cluster = [
    { id = 1, address = "0.0.0.0:9081", role = 1, status = 3 },
    { id = 2, address = "0.0.0.0:9082", role = 1, status = 3 },
    { id = 3, address = "0.0.0.0:9083", role = 1, status = 3 },
]

[raft.read_actor]
channel_capacity = 2048
max_drain = 1024

[raft.batching]
# Maximum number of commands to accumulate in a single batch during drain operations
max_batch_size = 200

[raft.persistence]
flush_policy = { Batch = { idle_flush_interval_ms = 1000 } }

[raft.metrics]
enable_backpressure = false
enable_batch = false

[raft.snapshot]
enable = false

[storage]
unified_db = false
