[cluster]
node_id = 2
listen_address = "0.0.0.0:9082"
initial_cluster = [
    { id = 1, address = "0.0.0.0:9081", role = 1, status = 3 },
    { id = 2, address = "0.0.0.0:9082", role = 1, status = 3 },
    { id = 3, address = "0.0.0.0:9083", role = 1, status = 3 },
]


[raft]
general_raft_timeout_duration_in_ms = 100

[raft.commit_handler]
batch_size = 5000


[raft.persistence]
flush_policy = { Batch = { idle_flush_interval_ms = 100 } }

[raft.snapshot]
enable = false
max_log_entries_before_snapshot = 10000
retained_log_entries = 3


# == Network Control Plane (voting, heartbeat, etc.) ==
[network.control]
tcp_keepalive_in_secs = 60             # Closer to native behavior
http2_keep_alive_interval_in_secs = 10
http2_keep_alive_timeout_in_secs = 5
connection_window_size = 2_097_152     # 2MB is sufficient (to prevent memory overflow)

# == Network Data Plane (append_entries, etc.) ==
[network.data]
connect_timeout_in_ms = 100            # Slow is fine, ensure the connection is established
request_timeout_in_ms = 300            # Log synchronization may take a long time.
tcp_keepalive_in_secs = 60
http2_keep_alive_interval_in_secs = 10
http2_keep_alive_timeout_in_secs = 5
connection_window_size = 4_194_304     # Increase the buffer size to support batch data.

# == Server Transport (single listener serving every RPC type) ==
[network.server]
concurrency_limit_per_connection = 30   # High concurrency supports data replication
max_concurrent_streams = 256            # Sufficient; higher values may be counterproductive
